config/routes.rb
Rails.application.routes.draw do

  get '', to: redirect("/#{I18n.locale}")

  scope '(:locale)', :locale => /ru|by|en/ do

    root 'index#index'

    devise_for :users, skip: :omniauth_callbacks

    match "/users/auth/:provider",
          constraints: { provider: /vkontakte|facebook/ },
          to: "omniauth_callbacks#passthru",
          as: :omniauth_authorize,
          via: [:get, :post]

    match "/users/auth/:action/callback",
          constraints: { action: /vkontakte|facebook/ },
          to: "omniauth_callbacks",
          as: :omniauth_callback,
          via: [:get, :post]

    resources :orders
    resources :products
    resources :product_attachments
    resources :product_properties
    resources :line_items do
      member do
        post 'increase', as: :increase
        post 'decrease', as: :decrease
      end

    end
    resources :carts

    post 'api/v' => 'store#render_cart_ico', as: :render_cart_ico
    get '404' => 'pages#not_found', as: :not_found
    get 'account' => 'users#account', as: :account
    get 'store' => 'store#index', as: :catalog
    get 'about' => 'pages#about', as: :about
    get 'help' => 'pages#help', as: :help

  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  PAYMENT_TYPES = [ 'Наличные', 'Кредитная карта', 'Другое' ]
  DELIVERY_TYPES = [ 'Курьером по Минску', 'Почтой по Беларуси', 'Другой' ]

  has_many :line_items, dependent: :destroy

  validates :last_name, :address, :phone, :email, :city, presence: true
  validates :zip_code, numericality: true,
                       length: {minimum: 6, maximum: 6},
                       presence: true
  validates :first_name,  presence: true,
                          length: {minimum: 2}
  validates :phone, presence: true,
                    numericality: true,
                    length: {minimum: 7, maximum: 17}
  validates :pay_type, inclusion: PAYMENT_TYPES
  validates :delivery_type, inclusion: DELIVERY_TYPES

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @orders = Order.all
    respond_with(@orders)
  end

  def show
    respond_with(@order)
  end

  def new
    if @cart.line_items.empty?
      redirect_to catalog_url
      return
    end
    if current_user.nil?
      @order = Order.new
      render action: 'new'
    else
      @order = Order.new() #TODO: сделать автозаполение полей заказа.
    end

  end

  def edit
  end

  def create
    @order = Order.new(order_params)
    @order.add_line_items_from_cart(@cart)

    if @order.save
      Cart.destroy(session[:cart_id])
      session[:cart_id] = nil
      OrderNotifier.received(@order).deliver
      OrderNotifier.new_order(@order).deliver
      redirect_to account_path
    else
      render action: 'new'
    end
  end

  def update
    @order.update(order_params)
    respond_with(@order)
  end

  def destroy
    @order.destroy
    respond_with(@order)
  end

  private
    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:first_name, :last_name, :address, :city, :zip_code, :phone, :email, :pay_type, :delivery_type)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.haml
.group.full-name
  .field.first-name
    = f.label t('orders.first_name')
    = f.text_field :first_name
  .field.last-name
    = f.label t('orders.last_name')
    = f.text_field :last_name
.field
  = f.label t('orders.address')
  = f.text_field :address, rows: 3, cols: 40
.group
  .field.city
    = f.label t('orders.city')
    = f.text_field :city
  .field.zip
    = f.label t('orders.zip_code')
    = f.text_field :zip_code
.field
  = f.label t('orders.email')
  = f.email_field :email
.field
  = f.label t('orders.phone')
  = f.phone_field :phone
.group
  .field.pay-type
    = f.label t('orders.pay_type')
    = f.select :pay_type, Order::PAYMENT_TYPES, prompt: '', validate: false
  .field.delivery-type
    = f.label t('orders.delivery_type')
    = f.select :delivery_type, Order::DELIVERY_TYPES, prompt: '', validate: false
.actions
  =link_to t('orders.next'), '#', remote: true, class: 'btn-submit next-step'

app/views/orders/_header.html.haml
.header-checkout
  .message-checkout
    %h4
      %strong
        = t('orders.checkout')
      %span.step-progress
        = t('orders.step')
        %span.step
        = t('orders.of')
        2
  =link_to root_path do
    = image_tag('image-logo-black.svg')
  .help-message
    %strong
      = t('orders.need_hand')
    = t('orders.talk_to_real')
    %br/
    %a{:href => "tel:+375-44-587-01-55"} +375-44-587-01-55

app/views/orders/_order.html.haml
.order
  #review-order-summary
    %div
      .order-summary
        %a.show-line-items-summary
          %dl.items
            %dt
              = "#{@cart.line_items.sum(:quantity)} #{t('cart.item')}"
            %dd
              = number_to_currency(@cart.subtotal_price)
        .line-items-summary
          - @cart.line_items.each do |item|
            .line-item
              =image_tag(item.product.product_attachments.first.image_url(:thumb), class: 'thumbnail')
              =link_to '', line_item_path(id: item.id, render_action: 'order'), method: :delete, class: 'remove', remote: true
              .line-item-price
                = number_to_currency(item.subtotal_price)
              .variant-name
                = "#{item.quantity} x #{item.product.title}"
              .variant-description
                %span
                  = item.product.product_properties.first.performance
                  = ' ' + item.product.product_properties.first.volume + t('product.ml')
              .clear
        %dl.shipping-dl
          %dt
            = t('cart.shipping')
          %dd $0.00
  -#        TODO: Настроить доставку и итоговую сумму.
  .promo
  .total
    #review-order-total.order-summary
      %div
        %dl.total
          %dt
            = t('cart.total')
          %dd $750.00

app/views/orders/edit.html.haml
%h1 Editing order

= render 'form'

= link_to 'Show', @order
\|
= link_to 'Back', orders_path

app/views/orders/index.html.haml
%h1 Listing orders

%table
  %thead
    %tr
      %th First name,
      %th Last name,
      %th Address
      %th City,
      %th Zip code,
      %th Phone,
      %th Email,
      %th Pay type,
      %th Delivery type
      %th
      %th
      %th
      
  %tbody
    - @orders.each do |order|
      %tr
        %td= order.first_name,
        %td= order.last_name,
        %td= order.address
        %td= order.city,
        %td= order.zip_code,
        %td= order.phone,
        %td= order.email,
        %td= order.pay_type,
        %td= order.delivery_type
        %td= link_to 'Show', order
        %td= link_to 'Edit', edit_order_path(order)
        %td= link_to 'Destroy', order, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Order', new_order_path

app/views/orders/items.js.erb
$('.order').replaceWith("<%= escape_javascript( render partial: 'orders/order') %>");
$('.order-summary').addClass('line-items-summary-active');

app/views/orders/new.html.haml
= render partial: 'orders/header'

.shipping{data: {step: 'checkout'}}
  = form_for @order, validate: true do |f|
    .checkout-step
      %div.foo.active
        %p.step-number I
        %h2.step-title
          = t('orders.shipping')
        .address
          %div
            .address-form
              = render 'form', :f => f
    .review
      %div.foo
        .click-guard
        %p.step-number II
        %h2.step-title
          = t('orders.review')
        =render 'orders/order'
        .field.buttons
          =link_to 'Редактировать данные', '#', class: 'btn-submit back', remote: true
          = f.submit 'Save', class: 'btn-submit apply'

app/views/orders/show.html.haml
%p#notice= notice

%p
  %b First name,:
  = @order.first_name,
%p
  %b Last name,:
  = @order.last_name,
%p
  %b Address:
  = @order.address
%p
  %b City,:
  = @order.city,
%p
  %b Zip code,:
  = @order.zip_code,
%p
  %b Phone,:
  = @order.phone,
%p
  %b Email,:
  = @order.email,
%p
  %b Pay type,:
  = @order.pay_type,
%p
  %b Delivery type:
  = @order.delivery_type

= link_to 'Edit', edit_order_path(@order)
\|
= link_to 'Back', orders_path