config/routes.rb
Rails.application.routes.draw do

  get '', to: redirect("/#{I18n.locale}")

  scope '(:locale)', :locale => /ru|by|en/ do

    root 'index#index'

    devise_for :users, skip: :omniauth_callbacks

    match "/users/auth/:provider",
          constraints: { provider: /vkontakte|facebook/ },
          to: "omniauth_callbacks#passthru",
          as: :omniauth_authorize,
          via: [:get, :post]

    match "/users/auth/:action/callback",
          constraints: { action: /vkontakte|facebook/ },
          to: "omniauth_callbacks",
          as: :omniauth_callback,
          via: [:get, :post]

    resources :orders
    resources :products
    resources :product_attachments
    resources :product_properties
    resources :line_items do
      member do
        post 'increase', as: :increase
        post 'decrease', as: :decrease
      end

    end
    resources :carts

    post 'api/v' => 'store#render_cart_ico', as: :render_cart_ico
    get '404' => 'pages#not_found', as: :not_found
    get 'account' => 'users#account', as: :account
    get 'store' => 'store#index', as: :catalog
    get 'about' => 'pages#about', as: :about
    get 'help' => 'pages#help', as: :help

  end

end

app/models/product_attachment.rb
class ProductAttachment < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  belongs_to :product
end

app/controllers/product_attachments_controller.rb
class ProductAttachmentsController < ApplicationController
  before_action :set_product_attachment, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @product_attachments = ProductAttachment.all
    respond_with(@product_attachments)
  end

  def show
    respond_with(@product_attachment)
  end

  def new
    @product_attachment = ProductAttachment.new
    respond_with(@product_attachment)
  end

  def edit
  end

  def create
    @product_attachment = ProductAttachment.new(product_attachment_params)
    @product_attachment.save
    respond_with(@product_attachment)
  end

  def update
    @product_attachment.update(product_attachment_params)
    respond_with(@product_attachment)
  end

  def destroy
    @product_attachment.destroy
    respond_with(@product_attachment)
  end

  private
    def set_product_attachment
      @product_attachment = ProductAttachment.find(params[:id])
    end

    def product_attachment_params
      params.require(:product_attachment).permit(:product_id, :image)
    end
end

app/helpers/product_attachments_helper.rb
module ProductAttachmentsHelper
end

app/views/product_attachments/_form.html.haml
= form_for @product_attachment do |f|
  - if @product_attachment.errors.any?
    #error_explanation
      %h2= "#{pluralize(@product_attachment.errors.count, "error")} prohibited this product_attachment from being saved:"
      %ul
        - @product_attachment.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :product_id
    = f.number_field :product_id
  .field
    = f.label :image
    = f.text_field :image
  .actions
    = f.submit 'Save'

app/views/product_attachments/edit.html.haml
%h1 Editing product_attachment

= render 'form'

= link_to 'Show', @product_attachment
\|
= link_to 'Back', product_attachments_path

app/views/product_attachments/index.html.haml
%h1 Listing product_attachments

%table
  %thead
    %tr
      %th Product
      %th Image
      %th
      %th
      %th
      
  %tbody
    - @product_attachments.each do |product_attachment|
      %tr
        %td= product_attachment.product_id
        %td= product_attachment.image
        %td= link_to 'Show', product_attachment
        %td= link_to 'Edit', edit_product_attachment_path(product_attachment)
        %td= link_to 'Destroy', product_attachment, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Product attachment', new_product_attachment_path

app/views/product_attachments/new.html.haml
%h1 New product_attachment

= render 'form'

= link_to 'Back', product_attachments_path

app/views/product_attachments/show.html.haml
%p#notice= notice

%p
  %b Product:
  = @product_attachment.product_id
%p
  %b Image:
  = @product_attachment.image

= link_to 'Edit', edit_product_attachment_path(@product_attachment)
\|
= link_to 'Back', product_attachments_path